### ISSUE TITLE
Bring back --new-image

### ISSUE THREAD

**Issue by onedr0p** [kiwicom/crane#6]
Greetings!

> Changed
> ⚠️ Breaking change: Instead of the whole URL passed via --new-image, Crane now only needs the new commit hash you want to deploy (via --new-commit). The value of this option defaults to the commit SHA the GitLab CI pipeline is running for, so in most cases you can just remove the --new-image option entirely.

Unless I am missing something your new method assumes you never want to deploy via Git Tags and only via Commit Refs.

For example, I want to deploy a new version of my app: `dtr.my-registry.com/app/app:1.0.11`

How is this possible with the `--new-commit` flag?

**Comment by underyx** [comment]
Hey @onedr0p, we didn't realize this use case is even possible, since there's assumptions made all over the place that you have an `old_version` and a `new_version`, which are commit SHAs and can be used to generate for instance the list of changes. While this assumption wasn't really explicitly warned about in the README, the usage instructions start out with

>1. Deploy your application on Rancher manually, with a *commit SHA tagged* image.

Right now I'm having a hard time figuring out a reason you'd use git tags instead of commit hashes for your image tags in GitLab CI. The only argument for this that I can imagine, is documentation and easier observability when operating production systems. What we do at @kiwicom is that we *label* the images

```
    --label build-date=`date -Iseconds`
    --label vcs-url=$CI_PROJECT_URL
    --label version=git-$CI_COMMIT_SHA
    --label com.kiwi.gitlab.ci.builder=$GITLAB_USER_EMAIL
    --label com.kiwi.gitlab.ci.pipeline=$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID
    --label com.kiwi.gitlab.ci.ref=$CI_COMMIT_REF_NAME
    --label com.kiwi.gitlab.ci.build=$CI_PROJECT_URL/builds/$CI_JOB_ID
```

And this gives you really nice visibility into what exactly is running on production on the Rancher UI:

![](https://i.underyx.me/2018-03-16T17-18-43.mo751.png)

Furthermore, while all images that get to production are commit hash tagged, for development and debugging we also tag them with the branch name:

```
    --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
```

So, with all this in mind, do you still see a reason to keep deploying git tagged images? If yes, I'm open to restoring the `--new-image` argument and removing the assumptions that there's an old and new commit hash in the 3.1 release.

**Comment by onedr0p** [comment]
Hi @underyx while I think it's a great idea to use docker labels to store that metadata, like you said using tagged images is nice in production environments.  Also, if you look at any public dockerhub images they are all versioned.

Additionally, it would also great to deploy a image on a different image repository like artifactory, not only Gitlabs registry.

If you could please bring it back that would be excellent.

Thanks.

**Comment by chauffer** [comment]
Hey @onedr0p.

As the original creator of crane, I wholeheartedly agree this should be a feature that should be kept around.

Our apologies for that, I can see my colleague @underyx is already working on bringing it back. :)

**Comment by onedr0p** [comment]
Thanks @chauffer and @underyx glad you all agree 👍

**Comment by underyx** [comment]
Hey @onedr0p, `kiwicom/crane:v3.1.0` is now published on Docker Hub with this implemented! Thanks for opening the issue; we're really glad to have feedback from the community, as it allows us to move faster with development by letting us know which corners we can and cannot cut. Let us know about any further feature requests!

**Comment by onedr0p** [comment]
@underyx looks like there is something odd happening still, see my https://github.com/kiwicom/crane/issues/8
